(function(){
  'use strict';
  const score=window.PIANO_SCORE;
  const ROWS=['1234567890-=','QWERTYUIOP[]',"ASDFGHJKL;'",'ZXCVBNM,./'];
  const STANDARD_LABELS=[..."Q2W3ER5T6Y7UI9O0PZSXDCFVBHNJM,L.;/'"];
  const SUPPLEMENTAL_LABELS=['A','G','K','1','4','8'];
  const special={',':'Comma','.':'Period',';':'Semicolon','/':'Slash',"'":'Quote','[':'BracketLeft',']':'BracketRight','-':'Minus','=':'Equal'};
  const codeFor=label=>special[label]||(/^\d$/.test(label)?'Digit':'Key')+label;
  const midi=note=>{const m=/^([A-G])([#b]?)(-?\d+)$/.exec(note),s={C:0,D:2,E:4,F:5,G:7,A:9,B:11};if(!m)throw new Error('Invalid note: '+note);return(+m[3]+1)*12+s[m[1]]+(m[2]==='#'?1:m[2]==='b'?-1:0);};
  const names=['C','C#','D','Eb','E','F','F#','G','Ab','A','Bb','B'];
  const noteFromMidi=value=>names[value%12]+(Math.floor(value/12)-1);
  const standardKeys=STANDARD_LABELS.map((label,x)=>({label,code:codeFor(label),x,base:48+x,hand:x<17?'L':'R',standard:true}));
  const supplementalKeys=SUPPLEMENTAL_LABELS.map(label=>({label,code:codeFor(label),supplemental:true}));
  const $=id=>document.getElementById(id);

  function uniqueTargets(input){const out=new Map();for(const target of input){const old=out.get(target.note);if(!old)out.set(target.note,{...target,hands:[...new Set(target.hands||[target.hand])]});else old.hands=[...new Set([...old.hands,...(target.hands||[target.hand])])];}return[...out.values()];}
  function metadata(previous){const fallback=[...previous.values()].find(binding=>Number.isFinite(binding.shift))?.shift||0,shift=Number.isFinite(previous.shift)?previous.shift:fallback;return{shift,shifts:previous.shifts||{L:shift,R:shift},split:Number.isFinite(previous.split)?previous.split:17};}
  function earlier(left,right){return left.some((value,index)=>value<right[index]&&left.slice(0,index).every((item,i)=>item===right[i]));}
  function allocate(input,previous=new Map(),locks=new Map()){
    const targets=uniqueTargets(input),wanted=targets.map(target=>target.note),old=metadata(previous),candidates=[];
    for(let shift=-48;shift<=72;shift+=12){const conflicts=wanted.filter(note=>{const pitch=midi(note);if([...locks.values()].some(locked=>midi(locked)===pitch))return false;const key=standardKeys[pitch-48-shift];return!key||(locks.has(key.code)&&midi(locks.get(key.code))!==pitch);}).length;candidates.push({shift,conflicts});}
    candidates.sort((a,b)=>a.conflicts-b.conflicts||Math.abs(a.shift-old.shift)-Math.abs(b.shift-old.shift)||Math.abs(a.shift)-Math.abs(b.shift));
    let shift=candidates[0]?.shift??old.shift,shifts={L:shift,R:shift},split=17,dual=false;
    if(candidates[0]?.conflicts){const pitches=wanted.map(midi),hands=wanted.map(note=>targets.find(target=>target.note===note)?.hands||[]);let best;for(const boundary of[17,...Array.from({length:15},(_,i)=>i+10).filter(value=>value!==17)]){const banks=['L','R'].map((hand,bank)=>{const options=[];for(let offset=-48;offset<=72;offset+=12){const covered=new Set(),matched=new Set();for(let i=0;i<pitches.length;i++){const x=pitches[i]-48-offset,key=standardKeys[x],inside=bank===0?x<boundary:x>=boundary;if(key&&inside&&(!locks.has(key.code)||midi(locks.get(key.code))===pitches[i])){covered.add(i);if(hands[i].includes(hand))matched.add(i);}}options.push({offset,covered,matched});}return options;});for(const left of banks[0])for(const right of banks[1]){const missing=pitches.length-new Set([...left.covered,...right.covered]).size,mismatch=pitches.length-new Set([...left.matched,...right.matched]).size,movement=Math.abs(left.offset-old.shifts.L)+Math.abs(right.offset-old.shifts.R),rank=[missing,mismatch,movement,Math.abs(boundary-old.split),Math.abs(left.offset)+Math.abs(right.offset)];if(!best||earlier(rank,best.rank))best={rank,split:boundary,shifts:{L:left.offset,R:right.offset}};}if(best?.rank[0]===0&&boundary===17)break;}if(best&&best.rank[0]<candidates[0].conflicts){shifts=best.shifts;split=best.split;dual=shifts.L!==shifts.R;shift=shifts.L;}}
    const byCode=new Map(),assigned=new Map();
    for(const key of standardKeys){const hand=key.x<split?'L':'R',offset=shifts[hand],pitch=key.base+offset;if(pitch>=0&&pitch<=127)byCode.set(key.code,{...key,hand,note:noteFromMidi(pitch),shift:offset});}
    for(const[code,pitch]of locks){const key=[...standardKeys,...supplementalKeys].find(item=>item.code===code);if(key)byCode.set(code,{...key,hand:key.supplemental?(previous.get(code)?.hand||'R'):key.x<split?'L':'R',note:pitch,shift:key.supplemental?0:midi(pitch)-key.base,locked:true});}
    for(const pitch of wanted){const hands=targets.find(target=>target.note===pitch)?.hands||[],bindings=[...byCode.values()].filter(binding=>midi(binding.note)===midi(pitch));bindings.sort((a,b)=>Number(b.locked||false)-Number(a.locked||false)||Number(hands.includes(b.hand))-Number(hands.includes(a.hand)));const binding=bindings[0];if(binding){const targetBinding={...binding,note:pitch};byCode.set(binding.code,targetBinding);assigned.set(pitch,targetBinding);}}
    const supplemental=[];for(const pitch of wanted){if(assigned.has(pitch))continue;const available=supplementalKeys.filter(key=>!byCode.has(key.code));available.sort((a,b)=>Number(previous.get(b.code)?.note===pitch)-Number(previous.get(a.code)?.note===pitch));const key=available[0];if(key){const binding={...key,note:pitch,hand:targets.find(target=>target.note===pitch)?.hands?.[0]||'R',shift:0};byCode.set(key.code,binding);assigned.set(pitch,binding);supplemental.push(binding);}}
    Object.assign(byCode,{shift,shifts,dual,split});return{byCode,targets:assigned,blocked:assigned.size!==wanted.length,shift,shifts,dual,split,supplemental};
  }

  function sourceGroups(){const map=new Map();for(const event of score.events){const id=event.bar+':'+event.tick;if(!map.has(id))map.set(id,{id,bar:event.bar,tick:event.tick,targets:[]});const group=map.get(id);for(const note of event.notes)group.targets.push({note,hand:event.hand,hands:[event.hand],role:event.hand==='R'?'melody':'accompaniment',duration:event.duration});}return[...map.values()].sort((a,b)=>a.bar-b.bar||a.tick-b.tick);}
  const allGroups=sourceGroups();
  let mode='auto',steps=[],index=0,running=false,mapping={byCode:new Map(),targets:new Map(),shift:0,shifts:{L:0,R:0}},held=new Map(),armed=new Set(),active=new Map(),chordStartedAt=null,chordExpired=false,attempts=0,correctNotes=0,correctGroups=0,mistakes=0,backingStartCount=0,audio=null,master=null,demoTimer=null;
  const keyEls=new Map(),voices=new Map();

  function userTargets(group){if(!group)return[];if(mode==='both')return group.targets;if(mode==='left')return group.targets.filter(target=>target.hand==='L');if(['auto','right','demo'].includes(mode))return group.targets.filter(target=>target.hand==='R');return[];}
  function rebuildSteps(){steps=mode==='free'?[]:allGroups.map(group=>({...group,targets:userTargets(group)})).filter(group=>group.targets.length);index=0;held.clear();armed.clear();active.clear();chordStartedAt=null;chordExpired=false;if(mode==='free'){const bindings=standardKeys.map(key=>({...key,note:noteFromMidi(key.base),shift:0}));const byCode=new Map(bindings.map(binding=>[binding.code,binding]));Object.assign(byCode,{shift:0,shifts:{L:0,R:0},dual:false,split:17});mapping={byCode,targets:new Map(bindings.map(binding=>[binding.note,binding])),shift:0,shifts:{L:0,R:0},dual:false,split:17,supplemental:[]};}else updateMapping();render();}
  function updateMapping(){mapping=allocate(steps[index]?.targets||[],mapping.byCode,held);}
  function canonicalPrompt(step,allocation){return(step?.targets||[]).map(target=>{const binding=allocation.targets.get(target.note);return{target,binding,label:binding?.label||'鼠标'};});}
  function applyPromptClasses(elements,prompt,className){const labels=new Set(prompt.map(item=>item.label.toUpperCase()));for(const element of elements){element.classList.remove('target','target-left','matched','demo-note');const label=element.querySelector('strong')?.textContent.toUpperCase(),match=labels.has(label);element.classList.toggle(className,match);if(match&&className==='target'){const item=prompt.find(entry=>entry.label.toUpperCase()===label);element.classList.toggle('target-left',item?.target.hands?.includes('L')&&!item?.target.hands?.includes('R'));}}}
  function currentPrompt(){return canonicalPrompt(steps[index],mapping);}

  function renderFlow(){const container=$('noteFlow').querySelector('.flow-notes');container.replaceChildren();if(mode==='free'){const group=document.createElement('div');group.className='flow-group current';group.style.left='28%';group.innerHTML='<span class="flow-letter">自由</span>';container.append(group);return;}for(let offset=-1;offset<=3;offset++){const step=steps[index+offset];if(!step)continue;const allocation=offset===0?mapping:allocate(step.targets,mapping.byCode,new Map()),prompt=canonicalPrompt(step,allocation),group=document.createElement('div');group.className='flow-group '+(offset===0?'current':offset<0?'past':'future');group.style.left=(28+offset*22)+'%';for(const item of prompt){const letter=document.createElement('span');letter.className='flow-letter';letter.textContent=item.label.toLowerCase();group.append(letter);}container.append(group);}}
  function renderKeyboard(){const prompt=mode==='free'?[]:currentPrompt();for(const[code,element]of keyEls){const binding=mapping.byCode.get(code);element.querySelector('small').textContent=binding?.note||'—';element.classList.toggle('inactive',!binding);element.classList.toggle('down',held.has(code));}applyPromptClasses(keyEls.values(),prompt,mode==='demo'?'demo-note':'target');$('mappingNotice').textContent=mapping.blocked?'需使用下方钢琴补弹':mapping.dual?'双手独立音区 · 左 '+mapping.shifts.L+' / 右 '+mapping.shifts.R:'固定键位 · 音区偏移 '+(mapping.shift||0);}
  function render(){renderFlow();renderKeyboard();$('progressText').textContent=mode==='free'?'自由演奏':index+' / '+steps.length+' 音组';$('progressBar').style.width=(100*index/Math.max(1,steps.length))+'%';$('completed').textContent=correctGroups;$('accuracy').textContent=attempts?Math.round(100*correctNotes/attempts)+'%':'—';$('mistakes').textContent=mistakes;$('status').textContent=!running?'已暂停':mode==='free'?'自由演奏中':mode==='demo'?'自动示范中':steps[index]?'等待当前音组':'已完成';}

  function ensureAudio(){if(!audio){audio=new(window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=$('volume').value/100;master.connect(audio.destination);}if(audio.state==='suspended')audio.resume();return audio;}
  function play(note,id=note){const ctx=ensureAudio(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='triangle';osc.frequency.value=440*Math.pow(2,(midi(note)-69)/12);gain.gain.setValueAtTime(.0001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.15,ctx.currentTime+.02);osc.connect(gain).connect(master);osc.start();voices.set(id,{osc,gain});}
  function stop(id){const voice=voices.get(id);if(!voice||!audio)return;voice.gain.gain.cancelScheduledValues(audio.currentTime);voice.gain.gain.setTargetAtTime(.0001,audio.currentTime,.05);voice.osc.stop(audio.currentTime+.3);voices.delete(id);}
  function stopAll(){for(const id of[...voices.keys()])stop(id);}
  function resetChord(){armed.clear();chordStartedAt=null;chordExpired=false;}
  function sourceFor(step){return allGroups.find(group=>group.id===step?.id);}
  function playBacking(step){for(const target of sourceFor(step)?.targets.filter(item=>item.hand==='L')||[]){const id='backing-'+backingStartCount++;play(target.note,id);setTimeout(()=>stop(id),420);}}
  function accept(){const step=steps[index],prompt=currentPrompt(),needed=prompt.map(item=>item.binding?.code).filter(Boolean);if(!step||chordExpired||needed.length!==prompt.length||!needed.every(code=>held.has(code)&&armed.has(code)))return false;for(const target of step.targets)active.set(target.note,target);if(mode==='auto')playBacking(step);correctGroups++;index++;resetChord();updateMapping();render();return true;}
  function press(code,inputTime=performance.now()/1000){if(!running||held.has(code))return'ignored';const binding=mapping.byCode.get(code);if(!binding)return'ignored';held.set(code,binding.note);attempts++;play(binding.note,code);const prompt=currentPrompt(),item=prompt.find(entry=>entry.binding?.code===code);if(mode==='free'){render();return'free';}if(!item){mistakes++;render();return'wrong';}if(chordStartedAt===null)chordStartedAt=inputTime;if(chordExpired||inputTime-chordStartedAt>.12+1e-7){chordExpired=true;armed.clear();mistakes++;render();return'late';}armed.add(code);correctNotes++;const result=accept()?'correct':'partial';render();return result;}
  function release(code){held.delete(code);armed.delete(code);stop(code);if(!(currentPrompt()).some(item=>held.has(item.binding?.code)))resetChord();render();}

  function stopDemo(){if(demoTimer){clearTimeout(demoTimer);demoTimer=null;}}
  function demoStep(){if(!running||mode!=='demo')return;const step=steps[index];if(!step){running=false;$('practiceToggle').textContent='▶ 再次示范';render();return;}updateMapping();render();const source=sourceFor(step);for(const target of source?.targets||[]){const id='demo-'+target.note+'-'+index;play(target.note,id);setTimeout(()=>stop(id),520);if(target.hand==='L')backingStartCount++;}demoTimer=setTimeout(()=>{index++;correctGroups++;updateMapping();render();demoStep();},850/Number($('speed').value));}

  for(const rowLabels of ROWS){const row=document.createElement('div');row.className='computer-row';for(const label of rowLabels){const code=codeFor(label),button=document.createElement('button');button.className='computer-key'+(STANDARD_LABELS.includes(label)?' standard':SUPPLEMENTAL_LABELS.includes(label)?' supplemental':' inactive');button.dataset.code=code;button.innerHTML='<strong>'+label+'</strong><small>—</small>';button.onpointerdown=()=>press(code);button.onpointerup=()=>release(code);button.onpointercancel=()=>release(code);row.append(button);keyEls.set(code,button);}$('computerKeyboard').append(row);}
  let white=0;for(let value=36;value<=96;value++){const black=[1,3,6,8,10].includes(value%12),button=document.createElement('button');button.className='piano-key'+(black?' black':'');button.innerHTML='<span>'+noteFromMidi(value)+'</span>';button.onpointerdown=()=>play(noteFromMidi(value),'piano-'+value);button.onpointerup=()=>stop('piano-'+value);if(black)button.style.left=(100/36*(white-.32))+'%';else white++;$('piano61').append(button);}

  document.addEventListener('keydown',event=>{if(!event.repeat&&keyEls.has(event.code)){event.preventDefault();press(event.code);}});document.addEventListener('keyup',event=>{if(keyEls.has(event.code)){event.preventDefault();release(event.code);}});window.addEventListener('blur',()=>{held.clear();resetChord();stopAll();render();});
  $('practiceToggle').onclick=()=>{running=!running;if(!running){held.clear();resetChord();stopAll();stopDemo();}$('practiceToggle').textContent=running?'Ⅱ 暂停跟练':'▶ 开始跟练';render();if(running&&mode==='demo')demoStep();};
  $('restart').onclick=()=>{running=false;attempts=correctNotes=correctGroups=mistakes=backingStartCount=0;stopDemo();stopAll();$('practiceToggle').textContent='▶ 开始跟练';rebuildSteps();};
  $('volume').oninput=event=>{if(master)master.gain.value=event.target.value/100;};
  for(const button of document.querySelectorAll('[data-mode]'))button.onclick=()=>{mode=button.dataset.mode;document.querySelectorAll('[data-mode]').forEach(item=>item.classList.toggle('selected',item===button));running=false;stopDemo();stopAll();$('practiceToggle').textContent='▶ 开始跟练';rebuildSteps();};
  window.PianoDemo={currentCodes:()=>currentPrompt().map(item=>item.binding?.code).filter(Boolean),backingStarts:()=>backingStartCount,stats:()=>({attempts,correctNotes,correctGroups,mistakes,index}),press,release,canonicalPrompt:()=>currentPrompt().map(item=>item.label)};
  rebuildSteps();
})();
