(function(){
  'use strict';
  const score=window.PIANO_SCORE;
  const midi=note=>{const m=/^([A-G])([#b]?)(-?\d+)$/.exec(note),semitones={C:0,D:2,E:4,F:5,G:7,A:9,B:11};return(+m[3]+1)*12+semitones[m[1]]+(m[2]==='#'?1:m[2]==='b'?-1:0);};
  const noteFromMidi=value=>{const names=['C','C#','D','Eb','E','F','F#','G','Ab','A','Bb','B'];return names[value%12]+(Math.floor(value/12)-1);};
  const preferred=new Set('ASDFJKLP');
  const keys=[...'QWERTYUIOP'].map((label,x)=>({label,x,hand:x<5?'L':'R'})).concat([...'ASDFGHJKL'].map((label,x)=>({label,x:x+.25,hand:x<5?'L':'R'}))).map(k=>({...k,code:'Key'+k.label}));
  const groups=()=>{const map=new Map();for(const event of score.events){const id=event.bar+':'+event.tick;if(!map.has(id))map.set(id,{bar:event.bar,tick:event.tick,targets:[]});for(const note of event.notes)map.get(id).targets.push({note,hand:event.hand});}return[...map.values()];};
  let mode='auto',steps=[],index=0,running=false,held=new Map(),mapping={byCode:new Map(),targets:new Map()},attempts=0,correct=0,backingStartCount=0,audio=null,master=null,metronomeTimer=null,demoTimer=null,beat=0;
  const $=id=>document.getElementById(id);
  function relevant(step){return{...step,targets:step.targets.filter(t=>mode==='both'||mode==='demo'||(mode==='left'&&t.hand==='L')||((mode==='right'||mode==='auto')&&t.hand==='R'))};}
  function allocate(targets,previous=mapping.byCode,locks=held){const byCode=new Map(),assigned=new Map();for(const[code,note]of locks){const key=keys.find(k=>k.code===code);if(key){const b={...key,note};byCode.set(code,b);assigned.set(note,b);}}for(const hand of['L','R']){const wanted=[...new Map(targets.filter(t=>t.hand===hand&&!assigned.has(t.note)).map(t=>[t.note,t])).values()].sort((a,b)=>midi(a.note)-midi(b.note));const available=keys.filter(k=>k.hand===hand&&!byCode.has(k.code)).sort((a,b)=>a.x-b.x);const cache=new Map();function choose(n,start){if(n===wanted.length)return{cost:0,list:[]};const id=n+':'+start;if(cache.has(id))return cache.get(id);let best={cost:Infinity,list:[]};for(let i=start;i<=available.length-(wanted.length-n);i++){const key=available[i],target=wanted[n],old=[...previous.values()].find(v=>v.note===target.note&&v.hand===hand);let cost=preferred.has(key.label)?0:5;if(old)cost+=old.code===key.code?-4:2;const tail=choose(n+1,i+1);if(cost+tail.cost<best.cost)best={cost:cost+tail.cost,list:[{...key,note:target.note},...tail.list]};}cache.set(id,best);return best;}for(const b of choose(0,0).list){byCode.set(b.code,b);assigned.set(b.note,b);}}return{byCode,targets:assigned};}
  function makeSteps(){index=0;if(mode==='free'){steps=[];const bindings=keys.map((key,i)=>({...key,note:noteFromMidi(48+i)}));mapping={byCode:new Map(bindings.map(b=>[b.code,b])),targets:new Map(bindings.map(b=>[b.note,b]))};for(const[code,el]of keyEls){const b=mapping.byCode.get(code);el.classList.add('target-key');el.classList.toggle('left-key',b.hand==='L');el.classList.toggle('right-key',b.hand==='R');el.querySelector('small').textContent='自由';}render();return;}steps=groups().map(relevant).filter(step=>step.targets.length);mapping={byCode:new Map(),targets:new Map()};updateMapping();}
  function updateMapping(){const current=steps[index];mapping=allocate(current?.targets||[]);for(const [code,el]of keyEls){const b=mapping.byCode.get(code);el.classList.toggle('target-key',!!b);el.classList.toggle('left-key',b?.hand==='L');el.classList.toggle('right-key',b?.hand==='R');el.querySelector('small').textContent=b?'当前':'—';}render();}
  function preview(step,previous){return allocate(step?.targets||[],previous,new Map());}
  function render(){const current=steps[index];$('promptMain').replaceChildren();if(mode==='free'){$('promptMain').textContent='自由演奏 · 19 个字母键';$('promptLabel').textContent=running?'按下任意高亮字母':'点击开始后自由演奏';}else if(current){for(const target of current.targets){const b=mapping.targets.get(target.note),chip=document.createElement('div');chip.className='target'+(target.hand==='L'?' left':'');chip.innerHTML='<kbd>'+b.label+'</kbd><span>'+(target.hand==='L'?'左手':'右手')+'</span>';$('promptMain').append(chip);}$('promptLabel').textContent=mode==='demo'?(running?'正在自动示范':'点击开始播放示范'):(running?'第 '+current.bar+' 小节 · 按齐高亮键':'准备好后点击开始跟练');}else $('promptMain').textContent='这一段弹完了！';$('queue').replaceChildren();let prior=mapping.byCode;for(let i=0;i<6;i++){const step=steps[index+i],tile=document.createElement('div');tile.className='tile'+(i===0?' current':'');if(mode==='free')tile.textContent=keys.slice(i*3,i*3+3).map(k=>k.label).join(' ');else if(step){const result=i===0?mapping:preview(step,prior);prior=result.byCode;tile.textContent=step.targets.map(t=>result.targets.get(t.note)?.label||'·').join(' ');}else tile.textContent='·';$('queue').append(tile);}$('progressText').textContent=mode==='free'?'自由演奏':index+' / '+steps.length+' 音组';$('progressBar').style.width=(100*index/Math.max(1,steps.length))+'%';$('completed').textContent=index;$('accuracy').textContent=attempts?Math.round(100*correct/attempts)+'%':'—';$('status').textContent=!running?'已暂停':mode==='free'?'自由演奏中':current?(mode==='demo'?'示范播放':'等待新音'):'已完成';}
  function playBacking(current){const source=groups().find(group=>group.bar===current.bar&&group.tick===current.tick);for(const target of source?.targets.filter(item=>item.hand==='L')||[]){backingStartCount++;play(target.note);setTimeout(()=>stop(target.note),320);}}
  function accept(){if(mode==='free'||mode==='demo')return;const current=steps[index];if(!current)return;const needed=current.targets.map(t=>mapping.targets.get(t.note)?.code);if(needed.every(code=>held.has(code))){correct+=needed.length;if(mode==='auto')playBacking(current);index++;held.clear();for(const el of keyEls.values())el.classList.remove('down');updateMapping();}}
  function press(code){if(!running||held.has(code))return;const b=mapping.byCode.get(code);attempts++;if(!b){render();return;}held.set(code,b.note);keyEls.get(code).classList.add('down');play(b.note);accept();render();}
  function release(code){held.delete(code);keyEls.get(code)?.classList.remove('down');stop(code);}
  const voices=new Map();function ensureAudio(){if(!audio){audio=new(window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=$('volume').value/100;master.connect(audio.destination);}return audio;}
  function play(note){const ctx=ensureAudio(),osc=ctx.createOscillator(),gain=ctx.createGain(),code=[...mapping.byCode].find(([,b])=>b.note===note)?.[0]||note;osc.type='triangle';osc.frequency.value=440*Math.pow(2,(midi(note)-69)/12);gain.gain.setValueAtTime(.0001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.18,ctx.currentTime+.02);osc.connect(gain).connect(master);osc.start();voices.set(code,{osc,gain});}
  function stop(code){const voice=voices.get(code);if(!voice)return;voice.gain.gain.cancelScheduledValues(audio.currentTime);voice.gain.gain.setTargetAtTime(.0001,audio.currentTime,.08);voice.osc.stop(audio.currentTime+.5);voices.delete(code);}
  function stopAll(){for(const code of [...voices.keys()])stop(code);}
  const keyEls=new Map();for(const letters of['QWERTYUIOP','ASDFGHJKL']){const row=document.createElement('div');row.className='computer-row';for(const letter of letters){const el=document.createElement('button');el.className='computer-key';el.dataset.code='Key'+letter;el.innerHTML='<strong>'+letter+'</strong><small>—</small>';el.onpointerdown=()=>press(el.dataset.code);el.onpointerup=()=>release(el.dataset.code);row.append(el);keyEls.set(el.dataset.code,el);}$('computerKeyboard').append(row);}
  let white=0;for(let n=36;n<=96;n++){const black=[1,3,6,8,10].includes(n%12),el=document.createElement('button');el.className='piano-key'+(black?' black':'');const names=['C','C♯','D','E♭','E','F','F♯','G','A♭','A','B♭','B'],name=names[n%12]+(Math.floor(n/12)-1);el.innerHTML='<span>'+name+'</span>';if(black){el.style.left=(100/36*(white-.31))+'%';}else white++;$('piano61').append(el);}
  document.addEventListener('keydown',e=>{if(!e.repeat&&keyEls.has(e.code)){e.preventDefault();press(e.code);}});document.addEventListener('keyup',e=>{if(keyEls.has(e.code)){e.preventDefault();release(e.code);}});window.addEventListener('blur',()=>{held.clear();stopAll();render();});
  function stopDemo(){if(demoTimer){clearTimeout(demoTimer);demoTimer=null;}}
  function advanceDemo(){if(!running||mode!=='demo')return;const current=steps[index];if(!current){running=false;$('practiceToggle').textContent='▶ 再次示范';render();return;}for(const target of current.targets)play(target.note);index++;updateMapping();const delay=500/+$('speed').value;demoTimer=setTimeout(()=>{stopAll();advanceDemo();},delay);}
  $('practiceToggle').onclick=()=>{running=!running;if(!running){held.clear();stopAll();stopDemo();}$('practiceToggle').textContent=running?'Ⅱ 暂停跟练':'▶ 开始跟练';render();if(running&&mode==='demo')advanceDemo();};$('restart').onclick=()=>{running=false;attempts=correct=0;held.clear();stopAll();stopDemo();makeSteps();};$('volume').oninput=e=>{if(master)master.gain.value=e.target.value/100;};
  for(const button of document.querySelectorAll('[data-mode]'))button.onclick=()=>{mode=button.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('selected',x===button));running=false;held.clear();stopAll();stopDemo();makeSteps();};
  function toggleMetronome(){if(metronomeTimer){clearInterval(metronomeTimer);metronomeTimer=null;$('metronome').classList.remove('running');$('metronomeToggle').textContent='▶ 开启节拍器';return;}ensureAudio();const speed=$('metronomeSpeed').value,bpm=speed==='custom'?+$('metronomeBpm').value:score.bpm*+speed;beat=0;const tick=()=>{beat=beat%score.timeSignature[0]+1;$('beatText').textContent=score.timeSignature.join('/')+' · 第 '+beat+' 拍';const osc=audio.createOscillator(),gain=audio.createGain();osc.frequency.value=beat===1?1100:800;gain.gain.setValueAtTime(.08,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.05);osc.connect(gain).connect(master);osc.start();osc.stop(audio.currentTime+.06);};tick();metronomeTimer=setInterval(tick,60000/bpm);$('metronome').classList.add('running');$('metronomeToggle').textContent='■ 关闭节拍器';}
  $('metronomeToggle').onclick=toggleMetronome;
  window.PianoDemo={currentCodes:()=>mode==='free'?[...mapping.byCode.keys()]:steps[index]?.targets.map(t=>mapping.targets.get(t.note)?.code).filter(Boolean)||[],backingStarts:()=>backingStartCount,showRest(){const h=$('promptMain').getBoundingClientRect().height;$('promptMain').textContent='休止 · 等待下一音';return h;},showWaiting(){render();$('promptLabel').textContent='等待你按齐这一组';}};
  makeSteps();
})();
